name: t
description: Telegram Client API (MTProto) to connect to Telegram and control a user programmatically.
version: 0.0.26
homepage: https://pwa.ir
repository: https://github.com/telegramflutter/t
topics:
 - telegram
 - tdlib

environment:
  sdk: ">=3.0.0 <4.0.0"


dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0

dependencies:
  equatable: ^2.0.7
  characters: ^1.4.0
  collection: ^1.19.1
  nop: ^0.2.0+3
  meta: any
  file: ^7.0.1
  path: ^1.9.1
